### PR TITLE
Migration

### PR DESCRIPTION
**Pull request by tobywf**
*Issue #, if available:* N/A

*Description of changes:* All good and building 🎉 🎅

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by tobywf** [comment]
Only thing I don't quite know how to do is running the SAM tests (which need docker) during the CI

**Review by seanmcl — APPROVED** [review]

**Review by Brimizer — APPROVED** [review]

**Comment by seanmcl** [comment]
@tobywf Yeah I've only ever run the sam tests locally.  Let's punt on making Travis do it.

**Comment by seanmcl** [comment]
@rjlohan Are you required to review every change to our handlers?

**Comment by rjlohan** [comment]
> @rjlohan Are you required to review every change to our handlers?

Hell no, ain't nobody got time for that. 😉 

I will review what I can, just to help out, but this is your repo and your destiny. If you have other service team members who you want to be maintainers of this repo, you can add them to your team, and then their reviews count towards the merge requirement.

**Comment by seanmcl** [comment]
@rjlohan ok cool.  I saw you were marked as 'requested' so didn't want to merge w/o checking with you.  I will ignore you from now on :)

**Pull request merged**
